### PR TITLE
Return empty string if requesting element longer than the list

### PR DESCRIPTION
**Pull request by Kerbas-ad-astra**
Per suggestion: http://forum.kerbalspaceprogram.com/threads/55219-1-0-x-ON-HOLD-Module-Manager-2-6-8-%28August-29th%29-With-more-SHA-and-less-bug-%28Upgrade-!!%29?p=2180270&viewfull=1#post2180270

### CODE REVIEW

**Comment by sarbian** [comment]
As I am away on vacation I can't merge it unless you add a version change in the request

**Comment by Kerbas-ad-astra** [comment]
Do I do this by editing AssemblyInfo.cs to bump the version number up to 2.6.10?

**Comment by sarbian** [comment]
Yes

**Comment by Kerbas-ad-astra** [comment]
Done!

**Comment by sarbian** [comment]
And merged. The Jenkins server should compile it in a minute. 
Thanks

**Pull request merged**
