### PR TITLE
Implemented Math on Vectors

### PR DESCRIPTION
**Pull request by ThomasKerman**
Hi Sarbian.
I was so free and implemented @Sigma88's specifications for Math on Vectors, as stated in #37 
It is a bit hacky, but I hope that you are fine with this. If not, I will redo it based on your opinion. :)

The syntax is pretty easy. If you have a node that looks like this:
```
NODE
{
    key = 0 1 0 1
    key = 1 0 1 0
    key = 1 1 0 0
    key = 0 0 1 1
}
```

and you do 
```
@NODE
{
    @key,*[0, ] += 1
}
```

you will get
```
NODE
{
    key = 1 1 0 1
    key = 2 0 1 0
    key = 2 1 0 0
    key = 1 0 1 1
}
```

The seperator (i.e. the part after **[index,**) defaults to ",", in this example I set it to a space. You can replace the index with a star to edit all the values in the vector.

I hope that you (and @Sigma88 ) will like it. :) If I broke something, please tell me and I will fix it ASAP.

Cheers!
-Thomas

### CODE REVIEW

**Comment by Sigma88** [comment]
<3

**Comment by sarbian** [comment]
:heart: :heart:  indeed.
It looks no more hacky than the rest of MM :+1: 
Can you include a bump of AssemblyVersion in  Properties/AssemblyInfo.cs so I can merge without fearing that jenkins overwirte the current version

**Comment by ThomasKerman** [comment]
Done :grinning:

**Comment by Sigma88** [comment]
thank you both @ThomasKerman  for the PR and @sarbian for merging it :+1:

may I bundle 2.6.14 into my mod that requires it? or should I wait for an official release?

**Comment by ThomasKerman** [comment]
@sarbian Sigma found a small issue, could you please replace the Regex on line 1455 with this one:
```private static Regex parseValue = new Regex(@"([\w\&\-\.\?\*]*)(?:,(-?[0-9\*]+))?(?:\[((?:[0-9\*]+)+)(?:,(.))?\])?(?:\s([+\-*/^!]))?");```

The issue is that the 3 group of the regex doesn't accept the star as a possible value, so ```@key[*] = something``` fails.

Sorry for that.

**Comment by sarbian** [comment]
Done. And don't worry, a contribution with a small bug is worth more than no contribution  :)

**Comment by sarbian** [comment]
@Sigma88  if you don't break RO/RSS with it I guess it is fine for distribution. 
I ll update the post in a few days.

**Comment by Sigma88** [comment]
I already have a warning in place to not use SigmaDimensions with RSS so it shouldn't be a problem.
and with this fix my mod should probably work fine with RSS. I'll leave the warning up for now, untill I can check everything is fine and compatible :D

**Pull request merged**
