### PR TITLE
A few more things

### PR DESCRIPTION
**Pull request by blowfishpro**
Figured out the performance issue in RO, turns out that it had to do with locking, fixed in `dc1a167`.  Also made various other improvements to help code quality/memory usage/performance.

Re: release - still waiting on a few PRs to fix some of the errors my changes have exposed.  I'd also like to give modders a chance to try a preview release of this so that they can identify these issues themselves (I know I didn't find all the mods that had them).

### CODE REVIEW

**Comment by blowfishpro** [comment]
OK if I post a test build in the thread?

**Comment by sarbian** [comment]
Of course.

**Comment by blowfishpro** [comment]
I think all the mods I identified as having problems have been fixed now, so this should be good to release

**Comment by sarbian** [comment]
Ok, I will into it Sunday.

**Pull request merged**
